### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by raphaelsimon1** [navin-hariharan/Master-Bomber#13]
not working at all

**Comment by navin-hariharan** [comment]
Yes! We are needing funds to host a server :)

**Comment by raphaelsimon1** [comment]
Good work

When you are ready please announce

From: Navin Hariharan ***@***.***>
Reply-To: navin-hariharan/Master-Bomber ***@***.***>
Date: Sunday, July 3, 2022 at 3:08 AM
To: navin-hariharan/Master-Bomber ***@***.***>
Cc: raphaelsimon1 ***@***.***>, Author ***@***.***>
Subject: Re: [navin-hariharan/Master-Bomber] not working at all (Issue #13)


Closed #13<https://github.com/navin-hariharan/Master-Bomber/issues/13> as completed.
