### ISSUE TITLE
Lolcat - Not found :/

### ISSUE THREAD

**Issue by Teknival** [navin-hariharan/Master-Bomber#2]
./Master-Bomber.sh: ligne 24: lolcat : commande introuvable
./Master-Bomber.sh: ligne 28: lolcat : commande introuvable
./Master-Bomber.sh: ligne 29: lolcat : commande introuvable
./Master-Bomber.sh: ligne 30: lolcat : commande introuvable
./Master-Bomber.sh: ligne 31: lolcat : commande introuvable
./Master-Bomber.sh: ligne 32: lolcat : commande introuvable
./Master-Bomber.sh: ligne 33: lolcat : commande introuvable
./Master-Bomber.sh: ligne 34: lolcat : commande introuvable
 Please Read Instruction Carefully !!! 
 
./Master-Bomber.sh: ligne 137: lolcat : commande introuvable
./Master-Bomber.sh: ligne 138: lolcat : commande introuvable
./Master-Bomber.sh: ligne 139: lolcat : commande introuvable
./Master-Bomber.sh: ligne 140: lolcat : commande introuvable

Hello Sir, 

I have installed Lolcat with snapd and I have this error ^^
Sorry for my skill i'm new in programing

Happy new Yeaaaaar Sir :)

**Comment by navin-hariharan** [comment]
Hello Teknival,
I see that lolcat is not working correctly! Just to confirm type the following in your terminal `echo Hello | lolcat` if this too gives you an error, Reinstall lolcat
