### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by zharavin** [navin-hariharan/Master-Bomber#3]
after install i run ./Master-Bomber.sh and saw this
./Master-Bomber.sh: line 28: lolcat: command not found
./Master-Bomber.sh: line 32: lolcat: command not found
./Master-Bomber.sh: line 33: lolcat: command not found
./Master-Bomber.sh: line 34: lolcat: command not found
./Master-Bomber.sh: line 35: lolcat: command not found
./Master-Bomber.sh: line 36: lolcat: command not found
./Master-Bomber.sh: line 37: lolcat: command not found
Press any key to continue...

**Comment by navin-hariharan** [comment]
Install lolcat
