### ISSUE TITLE
Cant run, Commands not found

### ISSUE THREAD

**Issue by BataBoom** [navin-hariharan/Master-Bomber#4]
./Master-Bomber.sh: line 28: toilet: command not found
./Master-Bomber.sh: line 28: boxes: command not found
./Master-Bomber.sh: line 28: lolcat: command not found
./Master-Bomber.sh: line 32: lolcat: command not found
./Master-Bomber.sh: line 33: lolcat: command not found
./Master-Bomber.sh: line 34: lolcat: command not found
./Master-Bomber.sh: line 35: lolcat: command not found
./Master-Bomber.sh: line 36: lolcat: command not found
./Master-Bomber.sh: line 37: lolcat: command not found

[>] Checking For Updates...
[+] [Up-To-Date]- v 021.1 -> Updated on JAN 05/2021 (navin-hariharan) | PATCH:2021.1.25
We could not install dependencies.

**Comment by Keasik** [comment]
sudo gem install lolcat

**Comment by navin-hariharan** [comment]
Please install lolcat or delete master-bomber with "`rm -rf Master-Bomber`" and  reinstall with the following command `pkg install git python;cd;if [ -d /scripts ]; then echo 'Exists'; else mkdir scripts;cd scripts;mkdir Social-Attacks; fi;cd Social-Attacks;git clone https://github.com/navin-hariharan/Master-Bomber;cd Master-Bomber;chmod +x *;./Master-Bomber.sh
`
